In [1]:
import requests

In [2]:
standings_url = "https://fbref.com/en/comps/9/Premier-League-Stats"

In [3]:
data = requests.get(standings_url)

In [4]:
from bs4 import BeautifulSoup

In [5]:
soup = BeautifulSoup(data.text)

In [6]:
standings_table = soup.select('table.stats_table')[0]

In [7]:
links = standings_table.find_all("a")

In [8]:
links = [l.get("href") for l in links]

In [9]:
links = [l for l in links if "/squads/" in l]

In [10]:
team_urls = [f"https://fbref.com{l}" for l in links]

In [11]:
team_urls

['https://fbref.com/en/squads/822bd0ba/Liverpool-Stats',
 'https://fbref.com/en/squads/cff3d9bb/Chelsea-Stats',
 'https://fbref.com/en/squads/18bb7c10/Arsenal-Stats',
 'https://fbref.com/en/squads/361ca564/Tottenham-Hotspur-Stats',
 'https://fbref.com/en/squads/d3fd31cc/Everton-Stats',
 'https://fbref.com/en/squads/8ef52968/Sunderland-Stats',
 'https://fbref.com/en/squads/4ba7cbea/Bournemouth-Stats',
 'https://fbref.com/en/squads/47c64c55/Crystal-Palace-Stats',
 'https://fbref.com/en/squads/19538871/Manchester-United-Stats',
 'https://fbref.com/en/squads/e4a775cb/Nottingham-Forest-Stats',
 'https://fbref.com/en/squads/d07537b9/Brighton-and-Hove-Albion-Stats',
 'https://fbref.com/en/squads/5bfb9659/Leeds-United-Stats',
 'https://fbref.com/en/squads/b8fd03ef/Manchester-City-Stats',
 'https://fbref.com/en/squads/943e8050/Burnley-Stats',
 'https://fbref.com/en/squads/cd051869/Brentford-Stats',
 'https://fbref.com/en/squads/7c21e445/West-Ham-United-Stats',
 'https://fbref.com/en/squads/b2b47a98/Newcastle-United-Stats',
 'https://fbref.com/en/squads/fd962109/Fulham-Stats',
 'https://fbref.com/en/squads/8602292d/Aston-Villa-Stats',
 'https://fbref.com/en/squads/8cec06e1/Wolverhampton-Wanderers-Stats']

In [12]:
team_url = team_urls[0]

In [13]:
data = requests.get(team_url)

In [14]:
import pandas as pd

matches = pd.read_html(data.text, match="Scores & Fixtures")

In [15]:
matches[0].head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,xG,xGA,Poss,Attendance,Captain,Formation,Opp Formation,Referee,Match Report,Notes
0,2025-08-10,15:00,FA Community Shield,FA Community Shield,Sun,Neutral,D,2 (2),2 (3),Crystal Palace,NaN,NaN,59.0,82645.0,Virgil van Dijk,4-2-3-1,3-4-3,Chris Kavanagh,Match Report,Crystal Palace won on penalty kicks following ...
1,2025-08-15,20:00,Premier League,Matchweek 1,Fri,Home,W,4,2,Bournemouth,2.2,1.7,61.0,60315.0,Virgil van Dijk,4-2-3-1,4-1-4-1,Anthony Taylor,Match Report,NaN
2,2025-08-25,20:00,Premier League,Matchweek 2,Mon,Away,W,3,2,Newcastle Utd,0.7,1.0,62.0,52230.0,Virgil van Dijk,4-2-3-1,4-3-3,Simon Hooper,Match Report,NaN
3,2025-08-31,16:30,Premier League,Matchweek 3,Sun,Home,W,1,0,Arsenal,0.5,0.5,53.0,NaN,Virgil van Dijk,4-2-3-1,4-3-3,Chris Kavanagh,Match Report,NaN
4,2025-09-14,14:00,Premier League,Matchweek 4,Sun,Away,NaN,NaN,NaN,Burnley,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Head-to-Head,NaN

In [16]:
soup = BeautifulSoup(data.text)

In [17]:
links = soup.find_all("a")

In [18]:
links = [l.get("href") for l in links]

In [19]:
links = [l for l in links if l and "all_comps/shooting/" in l]

In [20]:
links

['/en/squads/822bd0ba/2025-2026/matchlogs/all_comps/shooting/Liverpool-Match-Logs-All-Competitions',
 '/en/squads/822bd0ba/2025-2026/matchlogs/all_comps/shooting/Liverpool-Match-Logs-All-Competitions',
 '/en/squads/822bd0ba/2025-2026/matchlogs/all_comps/shooting/Liverpool-Match-Logs-All-Competitions',
 '/en/squads/822bd0ba/2025-2026/matchlogs/all_comps/shooting/Liverpool-Match-Logs-All-Competitions']

In [21]:
data = requests.get(f"https://fbref.com{links[0]}")

In [22]:
shooting = pd.read_html(data.text, match="Shooting")[0]

In [23]:
shooting.head()

  For Liverpool                                                        \
           Date   Time                 Comp                Round  Day
0    2025-08-10  15:00  FA Community Shield  FA Community Shield  Sun
1    2025-08-15  20:00       Premier League          Matchweek 1  Fri
2    2025-08-25  20:00       Premier League          Matchweek 2  Mon
3    2025-08-31  16:30       Premier League          Matchweek 3  Sun
4           NaN    NaN                  NaN                  NaN  NaN

                                                 ... Standard                \
     Venue Result     GF     GA        Opponent  ...     Dist   FK PK PKatt
0  Neutral      D  2 (2)  2 (3)  Crystal Palace  ...      NaN  NaN  0     0
1     Home      W      4      2     Bournemouth  ...     16.6  0.0  0     0
2     Away      W      3      2   Newcastle Utd  ...     19.3  0.0  0     0
3     Home      W      1      0         Arsenal  ...     22.4  1.0  0     0
4      NaN     --    NaN    NaN             NaN  ...     18.6  1.0  0     0

  Expected                            Unnamed: 25_level_0
        xG npxG npxG/Sh  G-xG np:G-xG        Match Report
0      NaN  NaN     NaN   NaN     NaN        Match Report
1      2.2  2.2    0.12   1.8     1.8        Match Report
2      0.7  0.7    0.14   2.3     2.3        Match Report
3      0.5  0.5    0.06   0.5     0.5        Match Report
4      NaN  NaN    0.10  10.0    10.0                 NaN

[5 rows x 26 columns]

In [24]:
shooting.columns = shooting.columns.droplevel()

In [25]:
shooting.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Match Report
0,2025-08-10,15:00,FA Community Shield,FA Community Shield,Sun,Neutral,D,2 (2),2 (3),Crystal Palace,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Match Report
1,2025-08-15,20:00,Premier League,Matchweek 1,Fri,Home,W,4,2,Bournemouth,...,16.6,0.0,0,0,2.2,2.2,0.12,1.8,1.8,Match Report
2,2025-08-25,20:00,Premier League,Matchweek 2,Mon,Away,W,3,2,Newcastle Utd,...,19.3,0.0,0,0,0.7,0.7,0.14,2.3,2.3,Match Report
3,2025-08-31,16:30,Premier League,Matchweek 3,Sun,Home,W,1,0,Arsenal,...,22.4,1.0,0,0,0.5,0.5,0.06,0.5,0.5,Match Report
4,NaN,NaN,NaN,NaN,NaN,NaN,--,NaN,NaN,NaN,...,18.6,1.0,0,0,NaN,NaN,0.10,10.0,10.0,NaN

In [26]:
shooting["Date"]

0    2025-08-10
1    2025-08-15
2    2025-08-25
3    2025-08-31
4           NaN
Name: Date, dtype: object

In [27]:
team_data = matches[0].merge(shooting[["Date", "Sh", "SoT", "Dist", "FK", "PK", "PKatt"]], on="Date")

In [28]:
team_data.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Opp Formation,Referee,Match Report,Notes,Sh,SoT,Dist,FK,PK,PKatt
0,2025-08-10,15:00,FA Community Shield,FA Community Shield,Sun,Neutral,D,2 (2),2 (3),Crystal Palace,...,3-4-3,Chris Kavanagh,Match Report,Crystal Palace won on penalty kicks following ...,12,5,NaN,NaN,0,0
1,2025-08-15,20:00,Premier League,Matchweek 1,Fri,Home,W,4,2,Bournemouth,...,4-1-4-1,Anthony Taylor,Match Report,NaN,19,10,16.6,0.0,0,0
2,2025-08-25,20:00,Premier League,Matchweek 2,Mon,Away,W,3,2,Newcastle Utd,...,4-3-3,Simon Hooper,Match Report,NaN,5,4,19.3,0.0,0,0
3,2025-08-31,16:30,Premier League,Matchweek 3,Sun,Home,W,1,0,Arsenal,...,4-3-3,Chris Kavanagh,Match Report,NaN,9,3,22.4,1.0,0,0

In [34]:
years = list(range(2025, 2023, -1))

In [35]:
years

[2025, 2024]

In [36]:
all_matches = []

In [37]:
standings_url = "https://fbref.com/en/comps/9/Premier-League-Stats"

In [ ]:
import time

for year in years:
    data = requests.get(standings_url)
    soup = BeautifulSoup(data.text)
    standings_table = soup.select("table.stats_table")[0]

    links = [l.get("href") for l in standings_table.find_all("a")]
    links = [l for l in links if "/squads/ in l"]
    team_urls = [f"https://fbref.com{l}" for l in links]

    previous_season = soup.select("a.prev")[0].get("href")
    standings_url = f"https://fbref.com/{previous_season}"

    for team_url in team_urls:
        team_name = team_url.split("/")[-1].replace("-Stats", "").replace("-"," ")

        data = requests.get(team_url)
        matches = pd.read_html(data.text, match="Scores & Fixtures")[0]

        soup = BeautifulSoup(data.text)
        links = [l.get("href") for l in soup.find_all("a")]
        links = [l for l in links if l and "all_comps/shooting/" in l]
        data = requests.get(f"https://fbref.com{links[0]}")
        shooting = pd.read_html(data.text, match="Shooting")[0]
        shooting.columns = shooting.columns.droplevel()

        try:
            team_data = matches.merge(shooting[["Date", "Sh", "SoT", "Dist", "FK", "PK", "PKatt"]], on="Date")
        except ValueError:
            continue

        team_data = team_data[team_data["Comp"] == "Premier League"]
        team_data["Season"] = year
        team_data["Team"] = team_name
        all_matches.append(team_data)

        time.sleep(1)

In [ ]:
match_df = pd.concat(all_matches)

'Liverpool'

In [ ]:
match_df.columns = [c.lower() for c in match_df.columns]

In [ ]:
match_df.to_csv("matches.csv")